const { chromium }=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext();const page=await context.newPage();
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://localhost:3000');
 await page.getByRole('button',{name:'Start application',exact:false}).first().click();
 await page.getByPlaceholder('Your full name').fill('Sample Workflow Client');
 await page.getByPlaceholder('you@example.com').fill('workflow@example.test');
 await page.getByPlaceholder('Your nationality').fill('Sample nationality');
 await page.getByPlaceholder('Use a sample value for this preview').fill('DO-NOT-STORE');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Application purpose').selectOption('Study');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Save sample request',exact:true}).click();
 await page.getByText('Your sample request is saved.',{exact:true}).waitFor();
 const reference=await page.evaluate(()=>localStorage.getItem('arrival-preview-reference'));assert.ok(reference.startsWith('REQ-'));
 const saved=await context.request.get('http://localhost:3000/api/demo/requests');const data=await saved.json();const record=data.records.find(r=>r.id===reference);assert.equal(record.status,'Submitted');assert.equal(record.enquiry.details.passport,undefined);
 await page.getByRole('link',{name:'View your sample request'}).click();
 await page.getByRole('heading',{name:'Study visa & permit support'}).waitFor();
 await page.goto('http://localhost:3000/admin');
 await page.getByLabel(`Update ${reference}`,{exact:true}).selectOption('Under review');
 await page.getByText('Sample status saved.',{exact:false}).waitFor();
 await page.getByRole('button',{name:reference,exact:false}).click();
 await page.getByText('workflow@example.test',{exact:false}).waitFor();
 await page.goto('http://localhost:3000/client');
 await page.getByRole('heading',{name:'Study visa & permit support'}).waitFor();
 assert.ok((await page.getByText('Under review',{exact:true}).count())>=2);
 await page.screenshot({path:'docs/preview-saved-request.png',fullPage:true});
 const malformed=await context.request.post('http://localhost:3000/api/demo/requests',{headers:{origin:'http://localhost:3000'},data:{service:'visa'}});assert.equal(malformed.status(),400);
 const foreign=await context.request.patch('http://localhost:3000/api/demo/requests',{headers:{origin:'https://untrusted.test'},data:{id:reference,status:'Confirmed'}});assert.equal(foreign.status(),403);
 const missing=await context.request.patch('http://localhost:3000/api/demo/requests',{headers:{origin:'http://localhost:3000'},data:{id:'missing',status:'Confirmed'}});assert.equal(missing.status(),404);
 await page.setViewportSize({width:390,height:844});await page.reload();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({reference,submission:true,adminUpdate:true,details:true,clientSync:true,validation:true,originGuard:true,mobile:true,pageErrors:errors}));
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
