"use client";
import { useState } from "react";
import Link from "next/link";
import { PageFrame, EnquiryButton } from "./page-frame";
import { RequestDialog } from "./request-dialog";
import { Button } from "@/components/ui/button";
import { packages } from "@/lib/packages";
export function PackagesOverview(){return <PageFrame><section className="content-hero"><span>PACKAGES</span><h1>Choose how much we coordinate.</h1><p>Compare responsibility and support, then open a package for the full scope. Supplier charges and government fees are separate.</p></section><div className="package-options">{packages.map((item,i)=><Link key={item.slug} href={`/packages/${item.slug}`}><span>0{i+1}</span><div><h2>{item.name}</h2><h3>{item.subtitle}</h3><p>{item.intro}</p><b>Inclusions, exclusions & quote →</b></div></Link>)}</div><section className="detail-section"><h2>Need a different combination?</h2><p>Choose individual services and share your requirements for a tailored quotation.</p><Link href="/packages/build">Build your own package →</Link></section></PageFrame>}
export function PackageDetail({slug}:{slug:string}){const item=packages.find(p=>p.slug===slug)!;const [open,setOpen]=useState(false);return <PageFrame><Link className="back-link" href="/packages">← All packages</Link><section className="content-hero"><span>{item.subtitle}</span><h1>{item.name}</h1><p>{item.intro}</p><Button onClick={()=>setOpen(true)}>Request a {item.name} quote</Button></section><div className="detail-columns">{[["Included support",item.includes],["Not included",item.excludes]].map(([title,points])=><section key={title as string}><h2>{title}</h2><ul>{(points as string[]).map(p=><li key={p}>{p}</li>)}</ul></section>)}</div><section className="detail-section"><h2>Who handles what</h2><p>{item.responsibility}</p></section><section className="detail-section"><h2>Pricing & quotation</h2><p>The agency fee is based on your travel purpose, dates, number of travellers and agreed scope. A quotation should identify the agency fee, official fees and supplier charges separately, with payment and cancellation terms. A confirmed public price schedule has not been supplied.</p><h2>What happens next</h2><p>Share your requirements, review the proposed scope and costs, then approve the arrangements. An enquiry does not confirm a booking or permit decision.</p><Link href="/packages/build">Customise your requirements →</Link></section><RequestDialog request={open?{service:"visa",package:item.name}:null} onClose={()=>setOpen(false)}/></PageFrame>}
const options=["Document preparation & review","Visa or permit coordination","Airport transfer","Accommodation assistance","Medical travel logistics","Family & companion planning","Local orientation","First-week support","Flight booking assistance","Car hire","Safari & activities","eSIM & connectivity"];
export function PackageBuilder(){const [selected,setSelected]=useState<string[]>([]);const [open,setOpen]=useState(false);return <PageFrame><Link className="back-link" href="/packages">← Packages</Link><section className="content-hero"><span>BUILD YOUR OWN</span><h1>A package around your plans.</h1><p>Select the services you need. Then add your contact and travel details to prepare a quote request.</p></section><fieldset className="builder-options"><legend>Choose your services</legend>{options.map(option=><label key={option}><input type="checkbox" checked={selected.includes(option)} onChange={e=>setSelected(current=>e.target.checked?[...current,option]:current.filter(item=>item!==option))}/>{option}</label>)}</fieldset><section className="detail-section"><h2>Your selection</h2>{selected.length?<ul>{selected.map(item=><li key={item}>{item}</li>)}</ul>:<p>Select at least one service to continue.</p>}<Button disabled={!selected.length} onClick={()=>setOpen(true)}>Continue to quote request</Button><p className="region-caption">The current workflow saves your request on this device. Email delivery needs to be connected before requests can reach the agency.</p></section><RequestDialog request={open?{service:"vacations",package:`Custom package: ${selected.join(", ")}`}:null} onClose={()=>setOpen(false)}/></PageFrame>}
