import Image from "next/image";
import Link from "next/link";
import { PageFrame, EnquiryButton } from "./page-frame";
import { regions, type Region, type Place } from "@/lib/destinations";

export function RegionGuide({ journey = false }: { journey?: boolean }) {
  if(journey) return <PageFrame><section className="content-hero"><span>YOUR JOURNEY</span><h1>One plan, from preparation to arrival.</h1><p>Your documents, travel, stay and appointments should fit together. See who handles each stage and what you need to do next.</p></section><ol className="journey-stages">{[
    ["Consultation","You share your purpose, nationality, dates and priorities. Your coordinator confirms what support can be offered.","You: travel goals and dates. Agency: proposed scope."],
    ["Documents & preparation","Receive a tailored checklist and prepare the supporting information. Missing items are identified before the next step.","You: accurate documents. Agency: preparation and review."],
    ["Official process","Follow the applicable visa or permit process. Your travel plan should account for the relevant authority’s requirements.","Authority: decisions. Agency: agreed coordination."],
    ["Flights & bookings","Review flight, stay and transfer options, their costs and cancellation conditions. Confirm arrangements in writing.","You: accept terms. Suppliers: booking confirmation."],
    ["Airport arrival","Use your confirmed meeting point and pickup details. Your itinerary should show the driver contact and accommodation destination.","Agency: coordination. Driver: confirmed pickup."],
    ["Stay & appointments","Settle in, attend planned appointments and follow your first-week checklist. Add local orientation or companion support if needed.","You: attend appointments. Coordinator: agreed follow-up."]
  ].map(([title,body,owner],i)=><li key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{title}</h2><p>{body}</p><small>{owner}</small></div></li>)}</ol><div className="detail-section"><h2>Build a plan around your purpose</h2><p>Work, study, family relocation, medical visits and holidays have different preparation needs. Choose an arrival package or combine individual services.</p><Link href="/packages">Compare packages →</Link><EnquiryButton>Discuss your arrival</EnquiryButton></div></PageFrame>;
  return <PageFrame service="vacations"><section className="content-hero"><span>DESTINATIONS</span><h1>All 14 regions. Your own way to explore.</h1><p>Choose a region for attractions, hotels, lodges and local stops. Open any place for practical visit information.</p></section><div className="regions-grid">{regions.map((region,i)=><Link className="region-link" href={`/destinations/${region.slug}`} key={region.slug}><span>{String(i+1).padStart(2,"0")}</span><h2>{region.name}</h2><p>{region.hub}</p><small>{region.places.length} places to explore →</small></Link>)}</div></PageFrame>;
}
export function RegionPage({region}:{region:Region}){return <PageFrame service="vacations"><Link className="back-link" href="/destinations">← All 14 regions</Link><section className="content-hero"><span>{region.hub}</span><h1>{region.name}</h1><p>{region.intro}</p></section><div className="places-grid">{region.places.map(place=><Link href={`/destinations/${region.slug}/${place.slug}`} key={place.slug} className="place-link"><span>{place.kind}</span><h2>{place.name}</h2><p>{place.description}</p><b>Visit information →</b></Link>)}</div><p className="region-caption">Places are suggestions, not agency partners or confirmed availability.</p></PageFrame>}
export function PlacePage({region,place}:{region:Region;place:Place}){return <PageFrame service="vacations"><Link className="back-link" href={`/destinations/${region.slug}`}>← Explore {region.name}</Link><section className="content-hero"><span>{region.name} / {place.kind}</span><h1>{place.name}</h1><p>{place.description}</p><EnquiryButton>Include this place in my plan</EnquiryButton></section><div className="detail-columns"><section><h2>Planning your visit</h2><p>Include your dates, number of travellers and starting point in the enquiry. We can discuss transport and a nearby stay around your wider route through {region.name}.</p></section><section><h2>What to confirm</h2><ul><li>Current opening hours or check-in arrangements</li><li>Access, reservation and entry requirements</li><li>Current fees and cancellation terms</li><li>Accessibility, driving time and seasonal conditions</li></ul></section><section><h2>Travel arrangements</h2><p>Tickets, accommodation, guided activities and meals are quoted separately unless included in your agreed package. A place enquiry does not reserve availability.</p><Link href="/services/vacations">Itinerary planning →</Link></section></div><section className="detail-section"><h2>More in {region.name}</h2><nav className="related-places">{region.places.filter(item=>item.slug!==place.slug).map(item=><Link key={item.slug} href={`/destinations/${region.slug}/${item.slug}`}>{item.name} →</Link>)}</nav></section></PageFrame>}
