import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { PageFrame, EnquiryButton } from "@/components/marketing/page-frame";
import { SectionHeading } from "@/components/ui/section-heading";
export const metadata:Metadata={title:"Explore Namibia | Arrival Namibia",description:"Browse Namibia travel ideas and ask about practical support for your visit."};
const places=[{name:"Windhoek",region:"Central Namibia",image:"namibia",text:"A practical starting point for an arrival, a city stay or onward travel."},{name:"Namib Desert",region:"Southern Namibia",image:"coast",text:"Ask about timing, transport and accommodation options for a desert visit."},{name:"Etosha region",region:"Northern Namibia",image:"travel",text:"Discuss a wildlife-focused stay and how it might fit your travel dates."},{name:"Atlantic coast",region:"Coastal Namibia",image:"stay",text:"Explore a coastal stop as part of a wider Namibian itinerary."}];
export default function DestinationsPage(){return <PageFrame><section className="content-hero"><span>DESTINATIONS / NAMIBIA</span><h1>Find your own way into Namibia.</h1><p>Explore a few starting points for a trip. Routes, availability and supplier details are confirmed for each enquiry.</p><EnquiryButton>Plan a trip</EnquiryButton></section><SectionHeading eyebrow="PLACES TO BEGIN" title="A country with room to roam.">Choose a place to start a conversation. These ideas are not fixed packages or live availability.</SectionHeading><div className="destination-grid">{places.map((place)=><article className="destination-card" key={place.name}><div className="destination-photo"><Image src={`/images/${place.image}.jpg`} alt={`${place.name} travel landscape`} fill sizes="(max-width: 700px) 90vw, 45vw" /></div><div><span>{place.region}</span><h2>{place.name}</h2><p>{place.text}</p><Link href="/services/vacations">Ask about a stay <ArrowRight size={15}/></Link></div></article>)}</div><aside className="service-note"><b>Need help with the practical details?</b><p>Discuss the travel dates, arrival transfer, accommodation and any paperwork support you may need.</p><Link href="/services">Explore services <ArrowRight size={15}/></Link></aside></PageFrame>}
